name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install pnpm globally
        run: npm install --quiet -g pnpm

      - name: Install packages
        run: pnpm install --frozen-lockfile

      - name: Run format check
        run: pnpm check:format